//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Post_Comment_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Comment
    {
        public int CommentId { get; set; }
        public string CommentDetails { get; set; }
        public int PostId { get; set; }
        public int Lid { get; set; }
        [XmlIgnore, JsonIgnore]
        public virtual Login Login { get; set; }
        public virtual Post Post { get; set; }
    }
}
